# Generated by Django 4.2.7 on 2023-12-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investcategory',
            name='max_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investcategory',
            name='usdt_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
