# Generated by Django 4.2.7 on 2023-12-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_investcategory_usdt_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='investcategory',
            name='usdt_max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
