# Generated by Django 4.2.7 on 2023-12-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_investcategory_usdt_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='investcategory',
            name='daily_withdrawal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investcategory',
            name='profit_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
