# Generated by Django 4.2.7 on 2023-12-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_package_paymentmethod_alter_investcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
