# Generated by Django 4.2.7 on 2023-12-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_alter_deposit_phone_alter_paymentmethod_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
