# Generated by Django 4.2.7 on 2023-12-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_withdrawal_is_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='package',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
        migrations.AddField(
            model_name='deposit',
            name='trans_ref',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
