# Generated by Django 4.2.7 on 2023-12-17 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0011_remove_deposit_package_remove_deposit_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='trans_ref',
        ),
        migrations.AddField(
            model_name='deposit',
            name='package',
            field=models.ForeignKey(default='ae088e5e-7616-4ee6-85a6-3a4f932169fc', on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='investments.package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='user',
            field=models.ForeignKey(default='76e60052-4692-475b-9f47-0ba9bf5f32e6', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
