# Generated by Django 4.2.7 on 2023-12-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_remove_deposit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='trans_ref',
            field=models.CharField(default='Test 1', max_length=100),
            preserve_default=False,
        ),
    ]
