# Generated by Django 4.2.7 on 2023-12-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_deposit_trans_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='package',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='trans_ref',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
