# Generated by Django 4.2.7 on 2023-12-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0015_remove_deposit_package_alter_deposit_trans_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='package',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='user',
        ),
    ]
