# Generated by Django 4.2.7 on 2023-12-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0016_remove_withdrawal_package_remove_withdrawal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='package',
            name='payment_method',
        ),
    ]
