# Generated by Django 4.2.7 on 2023-12-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0018_paymentmethod_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='short_name',
        ),
        migrations.AddField(
            model_name='investcategory',
            name='short_name',
            field=models.CharField(default='Category', max_length=255),
        ),
    ]
