# Generated by Django 4.2.7 on 2023-12-20 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0020_packagepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageWallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='investments.package')),
                ('amount', models.BigIntegerField(default=0)),
                ('withdrawable_amount', models.BigIntegerField(blank=True, null=True)),
                ('interest', models.BigIntegerField()),
                ('total_gained', models.BigIntegerField()),
                ('withdrawn_amount', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
