# Generated by Django 4.2.7 on 2023-12-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0021_packagewallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagewallet',
            name='withdrawable_amount',
            field=models.BigIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
