# Generated by Django 4.2.7 on 2023-12-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trialcheckout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrialCheckout',
        ),
    ]
