# Generated by Django 4.2.7 on 2023-12-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_trialcheckout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identification',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
