# Generated by Django 4.2.7 on 2023-12-13 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrialCheckout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('business_shortcode', models.PositiveBigIntegerField()),
                ('password', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=1000)),
                ('amount', models.PositiveBigIntegerField()),
                ('party_a', models.PositiveBigIntegerField()),
                ('party_b', models.PositiveBigIntegerField()),
                ('phone_number', models.PositiveBigIntegerField()),
                ('callback_url', models.URLField()),
                ('account_reference', models.CharField(max_length=1000)),
                ('transaction_description', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
